shopOwner: MyNameIsJan
location:
  x: 1
  y: 32
  z: 400
items:
  - {
    id: Dirt,
    enchantments:
      {DURABILITY: 2, SILK_TOUCH: 1, KNOCKBACK: 3},
    amountToSell: 1,
    priceToSell: 200,
    amountInStorage: 1
  }
  - {
    id: Dirt,
    enchantments:
      {DURABILITY: 2},
    amountToSell: 1,
    priceToSell: 200,
    amountInStorage: 1}